### ISSUE TITLE
I got too many files open do you have any solutions for this problem? 

### ISSUE THREAD

**Issue by spk921** [e-lab/imagenet-multiGPU.torch#5]
@jhjin  I am doing work to generate train and val set but I have following problem. 
My custom dataset has 56,1076. But imagenet has more but why I have following problem? 

/home/elab/torch/install/bin/luajit: create-dataset.lua:111: /home/elab/torch/install/share/lua/5.1/pl/dir.lua:257: cannot open /media/HDD1/edata2/edataSet2Depth1/table: Too many open files
stack traceback:
        [C]: in function '(for generator)'
        create-dataset.lua:111: in function 'create_dataset'
        create-dataset.lua:183: in main chunk
        [C]: in function 'dofile'
        ...elab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004065d0

**Comment by spk921** [comment]
One things is that I found many corrupted image files so I assume those are kept open. So is there are any option that I close those opened corrupted image files?

**Comment by spk921** [comment]
Also there is space in the name of the images is that matter?

**Comment by jhjin** [comment]
@spk921 having a space in the filename is something we wanna avoid. Why don't you try this https://github.com/e-lab/imagenet-multiGPU.torch/blob/master/tools/create-BIG-dataset.lua AFAIK, it has better error handling for corrupted images and is compatible with a very large dataset.

**Comment by spk921** [comment]
I solved a problem by filtering out corrupted one. Thank you I will use which you recommend.
