### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by rjuge** [e-lab/imagenet-multiGPU.torch#6]
Hi! I would like to use Enet for a university project, on object recognition. 
According to this post: https://culurciello.github.io/tech/2016/06/20/training-enet.html , I should be able to reach 68.4% on imagenet with the V12 architecture and the given training receipt but my results are around 10% worse. Any idea about this? (I also use the imagenet-multiGPU.torch scripts)

**Comment by culurciello** [comment]
modify the training regime as per:
https://culurciello.github.io/tech/2016/06/20/training-enet.html

**Comment by rjuge** [comment]
@culurciello thank you for answering.

I did use the following training regime:

```local lr, wd
local function paramsForEpoch(epoch)
if opt.LR ~= 0.0 and epoch == 1 then -- if manually specified	
	lr = opt.LR
	return { }
elseif epoch == 1 then
	lr = 0.1
	return { learningRate = lr, weightDecay=1e-4 }
elseif epoch > 15 then
	lr = lr * math.pow( 0.95, epoch - 15) 
	wd = 0 
	return { learningRate = lr, weightDecay=wd }, true
else
        wd = 1e-4
        return { learningRate = lr, weightDecay=wd }, true
end
end
```

Here are the results of EnetV12 using adam:
![enet1000adam](https://cloud.githubusercontent.com/assets/17725429/25745065/7ccc96c2-319d-11e7-9de0-d6d33d522fd2.png)
